feat: run lighthouse against live url

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -18,9 +18,13 @@ jobs:
       - name: Build
         run: |
           npm run build
+      - name: Wait for Netlify Deploy
+        uses: maddox/actions/wait-for-200@master
+        env:
+          URL: https://deploy-preview-54--jakepartusch.netlify.com/
       - name: Lighthouse CI
         run: |
           npm install -g @lhci/cli@0.3.x
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+          lhci autorun --upload.target=temporary-public-storage --url https://deploy-preview-54--jakepartusch.netlify.com/ || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
