Feature/lighthouse against live url (#55)
* feat: testing lighthouse github app

* feat: adding access token

* feat: run lighthouse against live url

* feat: trying out new Github action

* fix: try pull request action type

* fix: use output from previous action

* fix: fixing cli option to point to netlify url

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -1,6 +1,6 @@
 name: Lighthouse
 
-on: [push]
+on: [pull_request]
 
 jobs:
   build:
@@ -18,9 +18,14 @@ jobs:
       - name: Build
         run: |
           npm run build
+      - name: Waiting for 200 from the Netlify Preview
+        uses: jakepartusch/wait-for-netlify-action@v1
+        id: waitFor200
+        with:
+          site_name: "jakepartusch"
       - name: Lighthouse CI
         run: |
           npm install -g @lhci/cli@0.3.x
-          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
+          lhci autorun --upload.target=temporary-public-storage --collect.url=${{ steps.waitFor200.outputs.url }} || echo "LHCI failed!"
         env:
           LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
