feat: testing lighthouse github action and netlify plugin (#52)

diff --git a/.github/workflows/lighthouse.yml b/.github/workflows/lighthouse.yml
--- a/.github/workflows/lighthouse.yml
+++ b/.github/workflows/lighthouse.yml
@@ -1,4 +1,4 @@
-name: Build & Test
+name: Lighthouse
 
 on: [push]
 
@@ -18,6 +18,7 @@ jobs:
       - name: Build
         run: |
           npm run build
-      - name: Unit Tests
+      - name: Lighthouse CI
         run: |
-          npm test
+          npm install -g @lhci/cli@0.3.x
+          lhci autorun --upload.target=temporary-public-storage || echo "LHCI failed!"
